### PR TITLE
add Korean translation

### PR DESCRIPTION
**Pull request by appleparan**

### CODE REVIEW

**Comment by capajon** [comment]
Wow this is amazing!!

**Comment by capajon** [comment]
Looks good.  Sorry I didn't get to this earlier.  I'll make sure to release it to the site later today.  

Can I please add you to the credit/thanks section of the about page?  What name would you like me to put?  What URL?

Again, this is amazing.  Really happy to see this contribution. :)

**Comment by appleparan** [comment]
Thanks, I'm really appreciate about this page because I just bought R6 and
your page really helped me when learning maps.

Please add this to about section
LittleM0zart / https://game-rainbow6.ubi.com/es-mx/uplay/player-
statistics/53420818-60b0-4926-8621-09396295411b/multiplayer

**Comment by appleparan** [comment]
One more thing, I just report this issue.

https://github.com/capajon/r6maps/issues/28 it seems obvious mistake.
Please swap location of two names.

**Pull request merged**
