### PR TITLE
Added Russian translation for Theme Park map.

### PR DESCRIPTION
**Pull request by MasterGroosha**

### CODE REVIEW

**Comment by capajon** [comment]
Oh @MasterGroosha would you consider translating some of the new stats related terms in the general terms section?  There are a few new sections for r6maps.com/stats.html which I want to integrate soon.  If not, no worries, I appreciate all the help you've already done a lot!

**Comment by MasterGroosha** [comment]
Hmm..could you please point me to that section?

**Comment by capajon** [comment]
Yes - and 
https://github.com/capajon/r6maps/blob/master/dev/js/lang-terms/lang-terms.js#L178, 
https://github.com/capajon/r6maps/blob/master/dev/js/lang-terms/lang-terms.js#L195
https://github.com/capajon/r6maps/blob/master/dev/js/lang-terms/lang-terms.js#L204
https://github.com/capajon/r6maps/blob/master/dev/js/lang-terms/lang-terms.js#L209
https://github.com/capajon/r6maps/blob/master/dev/js/lang-terms/lang-terms.js#L218 (not sure if operators are translated though)

**Comment by MasterGroosha** [comment]
Will try.

**Comment by capajon** [comment]
Thanks!  I know it is quite a few terms so appreciate any help with it.

**Comment by MasterGroosha** [comment]
@capajon Is it possible somehow to test new "Stats" feature? To check language.

**Pull request merged**
